project:
  type: book

bibliography: references.bib

book:
  title: "Learn-R"
  author: "Shitao Wu"
  date: "2022/8/3"
  cover-image: images/Rlogo.png

  reader-mode: true
  site-url: https://shitao.quarto.pub/learn-r/
  repo-url: https://github.com/Shitao5/learn-r
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - preface.qmd

    - part: Visualisation
      chapters:
        - vis-intro.qmd
        - vis-ggplot2.qmd

    - part: Finance
      chapters:
        - fin-intro.qmd
        - fin-tidy.qmd

    - references.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-copy: hover
    code-link: true
    include-in-header: "plausible.html"
  # pdf:
  #   documentclass: scrreprt



