project:
  type: book

bibliography: references.bib
number-sections: true
number-depth: 3
toc-depth: 4
crossref:
  fig-title: 图
  fig-prefix: 图
  tbl-title: 表
  tbl-prefix: 表
execute:
  freeze: true

book:
  title: "Learn-R"
  author: "Shitao Wu"
  date: "2022/8/3"
  cover-image: images/Rlogo.png
  search: true
  # downloads: [pdf, epub]
  page-footer:
    center: "© Shitao Wu 2022"
    # background: light
    # right:
    #   - icon: github
    #     href: https://github.com/Shitao5

  reader-mode: true
  site-url: https://shitao.quarto.pub/learn-r/
  repo-url: https://github.com/Shitao5/learn-r
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - preface.qmd

    - part: R Project
      chapters:
        - r-inferno.qmd

    - part: Visualisation.qmd
      chapters:
        - vis-ggplot2-layers.qmd
        - vis-ggplot2-scales.qmd
        - vis-ggplot2-grammar.qmd

    - part: Modeling
      chapters:
        - mod-tidy1.qmd

    - part: Shiny.qmd
      chapters:
        - shiny1.qmd

    - part: Finance.qmd
      chapters:
        - fin-tidy.qmd

    - references.qmd

# comments:
#   hypothesis: true

format:
  html:
    theme: [cosmo, custom.scss]
    code-copy: hover
    code-link: true
    include-in-header: "plausible.html"

  # pdf:
  #   documentclass: scrreprt
